/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AutomationCompatibleInterface,
  AutomationCompatibleInterfaceInterface,
} from "../../../../../../../@chainlink/contracts/src/v0.8/automation/interfaces/AutomationCompatibleInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "checkData",
        type: "bytes",
      },
    ],
    name: "checkUpkeep",
    outputs: [
      {
        internalType: "bool",
        name: "upkeepNeeded",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "performData",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "performData",
        type: "bytes",
      },
    ],
    name: "performUpkeep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class AutomationCompatibleInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AutomationCompatibleInterfaceInterface {
    return new Interface(_abi) as AutomationCompatibleInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AutomationCompatibleInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AutomationCompatibleInterface;
  }
}
