[profile.default]
fs_permissions = [{access = "read", path = "lib/foundry-chainlink-toolkit/out"}]
gas_reports = ["*"]
libs = ['lib']
out = 'out'
solc-version = "0.8.20"
src = 'src'
test = 'src/test'

[fmt]
line_length = 100
bracket_spacing = false
wrap_comments = true

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config
