/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IOracleInterface extends Interface {
  getFunction(nameOrSignature: "addRequest" | "fallbackCall"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addRequest",
    values: [AddressLike, BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fallbackCall",
    values: [AddressLike, BytesLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fallbackCall",
    data: BytesLike
  ): Result;
}

export interface IOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IOracle;
  waitForDeployment(): Promise<this>;

  interface: IOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRequest: TypedContractMethod<
    [
      callbackContract: AddressLike,
      callbackArgs: BytesLike,
      nonce: BigNumberish,
      sender: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;

  fallbackCall: TypedContractMethod<
    [
      callbackContract: AddressLike,
      callbackArgs: BytesLike,
      nonce: BigNumberish,
      sender: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRequest"
  ): TypedContractMethod<
    [
      callbackContract: AddressLike,
      callbackArgs: BytesLike,
      nonce: BigNumberish,
      sender: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fallbackCall"
  ): TypedContractMethod<
    [
      callbackContract: AddressLike,
      callbackArgs: BytesLike,
      nonce: BigNumberish,
      sender: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
