name: Setup

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        cache: "npm"
        node-version: 18.x
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          '**/node_modules'
          '**/lib/forge-std'
        key: ${{ hashFiles('**/lib/forge-std/package.json') }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: make install-ci
      if: steps.cache.outputs.cache-hit != 'true'