/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracleInterfacesSol from "./OracleInterfaces.sol";
export type { oracleInterfacesSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { DataStreamsConsumer } from "./DataStreamsConsumer";
