/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  KeeperRegistryMock,
  KeeperRegistryMockInterface,
} from "../../../contracts/mocks/KeeperRegistryMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "upkeep",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "performData",
        type: "bytes",
      },
    ],
    name: "performUpkeep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506103a6806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80633085f08a14610030575b600080fd5b61004a60048036038101906100459190610273565b61004c565b005b8173ffffffffffffffffffffffffffffffffffffffff16634585e33b826040518263ffffffff1660e01b8152600401610085919061034e565b600060405180830381600087803b15801561009f57600080fd5b505af11580156100b3573d6000803e3d6000fd5b505050505050565b6000604051905090565b600080fd5b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100fa826100cf565b9050919050565b61010a816100ef565b811461011557600080fd5b50565b60008135905061012781610101565b92915050565b600080fd5b600080fd5b6000601f19601f8301169050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b61018082610137565b810181811067ffffffffffffffff8211171561019f5761019e610148565b5b80604052505050565b60006101b26100bb565b90506101be8282610177565b919050565b600067ffffffffffffffff8211156101de576101dd610148565b5b6101e782610137565b9050602081019050919050565b82818337600083830152505050565b6000610216610211846101c3565b6101a8565b90508281526020810184848401111561023257610231610132565b5b61023d8482856101f4565b509392505050565b600082601f83011261025a5761025961012d565b5b813561026a848260208601610203565b91505092915050565b6000806040838503121561028a576102896100c5565b5b600061029885828601610118565b925050602083013567ffffffffffffffff8111156102b9576102b86100ca565b5b6102c585828601610245565b9150509250929050565b600081519050919050565b600082825260208201905092915050565b60005b838110156103095780820151818401526020810190506102ee565b60008484015250505050565b6000610320826102cf565b61032a81856102da565b935061033a8185602086016102eb565b61034381610137565b840191505092915050565b600060208201905081810360008301526103688184610315565b90509291505056fea2646970667358221220fd1452d32fcc47810149410957920aa5595eae0124126245ca2f165c5a5053b364736f6c63430008130033";

type KeeperRegistryMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: KeeperRegistryMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class KeeperRegistryMock__factory extends ContractFactory {
  constructor(...args: KeeperRegistryMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      KeeperRegistryMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): KeeperRegistryMock__factory {
    return super.connect(runner) as KeeperRegistryMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KeeperRegistryMockInterface {
    return new Interface(_abi) as KeeperRegistryMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): KeeperRegistryMock {
    return new Contract(address, _abi, runner) as unknown as KeeperRegistryMock;
  }
}
