/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as oracleInterfacesSol from "./OracleInterfaces.sol";
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { DataStreamsConsumer__factory } from "./DataStreamsConsumer__factory";
