/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutomationCompatibleInterface } from "./AutomationCompatibleInterface";
export type { ILogAutomation } from "./ILogAutomation";
export type { StreamsLookupCompatibleInterface } from "./StreamsLookupCompatibleInterface";
